[package]
name = "gollum"
version = "0.0.0"
edition = "2021"

[dependencies]
axum = "0.5.17"
tokio = { version = "1.21.2", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["json", "env-filter"] }
